### ISSUE TITLE
Save the URL of the source-archives in `.packit.yaml`

### ISSUE THREAD

**Issue by csomh** [packit/dist-git-to-source-git#179]
Instead of commiting the source-archives when converting/updating a source-git repo from a dist-git repo, create a `sources` entry in `.packit.yaml` for each archive mentioned in the metadata file (`.<package>.metadata`), specifying the download URL of those archives.

Note that `packit srpm` currently expects source-archives to be found in the `SPECS` sub-directory.

For example, when processing the `c8s` branch of `rsync`:

```
$ cat .rsync.metadata
82e7829c0b3cefbd33c233005341e2073c425629 SOURCES/rsync-3.1.3.tar.gz
74c16510a18ef43d797f9ceba6150f0862568cc0 SOURCES/rsync-patches-3.1.3.tar.gz
```

Based on this `.packit.yaml` should contain:

```yaml
sources:
  - path: SPECS/rsync-3.1.3.tar.gz
    url: https://git.centos.org/sources/rsync/c8s/82e7829c0b3cefbd33c233005341e2073c425629
  - path: SPECS/rsync-3.1.3.tar.gz
    url: https://git.centos.org/sources/rsync/c8s/74c16510a18ef43d797f9ceba6150f0862568cc0
```

This should be done after packit/packit#1105 is implemented.
